/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Administrator
 */
public class Menu3Form extends javax.swing.JPanel {

    /**
     * Creates new form Menu3Form
     */
    public Menu3Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sPnlMemberBackground = new javax.swing.JScrollPane();
        tPnlMembers = new View.Components.TabbedPaneCustom.TabbedPaneCustom();
        tPnlMadd = new java.awt.Panel();
        tPnlMupdate = new java.awt.Panel();
        tPnlMdelete = new java.awt.Panel();
        iPnlAccountHed = new View.Components.ImagePanel.ImageAvatar();

        tPnlMembers.setBackground(new java.awt.Color(173, 139, 142));
        tPnlMembers.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout tPnlMaddLayout = new javax.swing.GroupLayout(tPnlMadd);
        tPnlMadd.setLayout(tPnlMaddLayout);
        tPnlMaddLayout.setHorizontalGroup(
            tPnlMaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        tPnlMaddLayout.setVerticalGroup(
            tPnlMaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        tPnlMembers.addTab("Add", tPnlMadd);

        javax.swing.GroupLayout tPnlMupdateLayout = new javax.swing.GroupLayout(tPnlMupdate);
        tPnlMupdate.setLayout(tPnlMupdateLayout);
        tPnlMupdateLayout.setHorizontalGroup(
            tPnlMupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        tPnlMupdateLayout.setVerticalGroup(
            tPnlMupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        tPnlMembers.addTab("Update", tPnlMupdate);

        javax.swing.GroupLayout tPnlMdeleteLayout = new javax.swing.GroupLayout(tPnlMdelete);
        tPnlMdelete.setLayout(tPnlMdeleteLayout);
        tPnlMdeleteLayout.setHorizontalGroup(
            tPnlMdeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        tPnlMdeleteLayout.setVerticalGroup(
            tPnlMdeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        tPnlMembers.addTab("Delete", tPnlMdelete);

        sPnlMemberBackground.setViewportView(tPnlMembers);

        jScrollPane1.setViewportView(sPnlMemberBackground);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addComponent(iPnlAccountHed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iPnlAccountHed, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.Components.ImagePanel.ImageAvatar iPnlAccountHed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane sPnlMemberBackground;
    private java.awt.Panel tPnlMadd;
    private java.awt.Panel tPnlMdelete;
    private View.Components.TabbedPaneCustom.TabbedPaneCustom tPnlMembers;
    private java.awt.Panel tPnlMupdate;
    // End of variables declaration//GEN-END:variables
}
