/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Administrator
 */
public class Menu2Form extends javax.swing.JPanel {

    /**
     * Creates new form Menu2Form
     */
    public Menu2Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPnlBooks = new View.Components.TabbedPaneCustom.TabbedPaneCustom();
        tPnlBadd = new java.awt.Panel();
        tPnlBupdate = new java.awt.Panel();
        tPnlBdelete = new java.awt.Panel();
        iPnlBookHed = new View.Components.ImagePanel.ImageAvatar();

        tPnlBooks.setBackground(new java.awt.Color(255, 255, 255));
        tPnlBooks.setForeground(new java.awt.Color(0, 0, 255));

        tPnlBadd.setFont(new java.awt.Font("Dubai", 3, 15)); // NOI18N

        javax.swing.GroupLayout tPnlBaddLayout = new javax.swing.GroupLayout(tPnlBadd);
        tPnlBadd.setLayout(tPnlBaddLayout);
        tPnlBaddLayout.setHorizontalGroup(
            tPnlBaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        tPnlBaddLayout.setVerticalGroup(
            tPnlBaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        tPnlBooks.addTab("Add", tPnlBadd);

        tPnlBupdate.setFont(new java.awt.Font("Dubai", 3, 15)); // NOI18N

        javax.swing.GroupLayout tPnlBupdateLayout = new javax.swing.GroupLayout(tPnlBupdate);
        tPnlBupdate.setLayout(tPnlBupdateLayout);
        tPnlBupdateLayout.setHorizontalGroup(
            tPnlBupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        tPnlBupdateLayout.setVerticalGroup(
            tPnlBupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        tPnlBooks.addTab("Update", tPnlBupdate);

        tPnlBdelete.setFont(new java.awt.Font("Dubai", 3, 15)); // NOI18N

        javax.swing.GroupLayout tPnlBdeleteLayout = new javax.swing.GroupLayout(tPnlBdelete);
        tPnlBdelete.setLayout(tPnlBdeleteLayout);
        tPnlBdeleteLayout.setHorizontalGroup(
            tPnlBdeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        tPnlBdeleteLayout.setVerticalGroup(
            tPnlBdeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        tPnlBooks.addTab("Delete", tPnlBdelete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iPnlBookHed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tPnlBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iPnlBookHed, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPnlBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.Components.ImagePanel.ImageAvatar iPnlBookHed;
    private java.awt.Panel tPnlBadd;
    private java.awt.Panel tPnlBdelete;
    private View.Components.TabbedPaneCustom.TabbedPaneCustom tPnlBooks;
    private java.awt.Panel tPnlBupdate;
    // End of variables declaration//GEN-END:variables
}
